### ISSUE TITLE
Exception: Missing user_loader or request_loader.

### ISSUE THREAD

**Issue by geolectric** [wuttem/flask-ad-auth#3]
When I try to run this I get the error:

Exception: Missing user_loader or request_loader.

**Comment by wuttem** [comment]
Could you copy&paste the Stacktrace and the output of `pip freeze`?
Maybe its a problem with a specific version of a library ...

**Comment by nawangwe** [comment]
Any solution for this problem yet?

**Comment by wuttem** [comment]
That was quite some time ago and i could not replicate the error with my setup ... do you get the same error ? can you provide some additional information ?

**Comment by KrennKristof** [comment]
got the same error with the following stacktrace:

../ENV/lib/python3.8/site-packages/werkzeug/test.py:1006: in get
    return self.open(*args, **kw)
../ENV/lib/python3.8/site-packages/flask/testing.py:222: in open
    return Client.open(
../ENV/lib/python3.8/site-packages/werkzeug/test.py:970: in open
    response = self.run_wsgi_app(environ.copy(), buffered=buffered)
../ENV/lib/python3.8/site-packages/werkzeug/test.py:861: in run_wsgi_app
    rv = run_wsgi_app(self.application, environ, buffered=buffered)
../ENV/lib/python3.8/site-packages/werkzeug/test.py:1096: in run_wsgi_app
    app_rv = app(environ, start_response)
../ENV/lib/python3.8/site-packages/flask/app.py:2464: in __call__
    return self.wsgi_app(environ, start_response)
../ENV/lib/python3.8/site-packages/flask/app.py:2450: in wsgi_app
    response = self.handle_exception(e)
../ENV/lib/python3.8/site-packages/flask_cors/extension.py:165: in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
../ENV/lib/python3.8/site-packages/flask/app.py:1867: in handle_exception
    reraise(exc_type, exc_value, tb)
../ENV/lib/python3.8/site-packages/flask/_compat.py:39: in reraise
    raise value
../ENV/lib/python3.8/site-packages/flask/app.py:2447: in wsgi_app
    response = self.full_dispatch_request()
../ENV/lib/python3.8/site-packages/flask/app.py:1952: in full_dispatch_request
    rv = self.handle_user_exception(e)
../ENV/lib/python3.8/site-packages/flask_cors/extension.py:165: in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
../ENV/lib/python3.8/site-packages/flask/app.py:1821: in handle_user_exception
    reraise(exc_type, exc_value, tb)
../ENV/lib/python3.8/site-packages/flask/_compat.py:39: in reraise
    raise value
../ENV/lib/python3.8/site-packages/flask/app.py:1948: in full_dispatch_request
    rv = self.preprocess_request()
../ENV/lib/python3.8/site-packages/flask/app.py:2242: in preprocess_request
    rv = func()
adminpanel/core/auth.py:63: in redirect_unauthorized
    if not current_user or not current_user.is_authenticated:
../ENV/lib/python3.8/site-packages/werkzeug/local.py:328: in __bool__
    return bool(self._get_current_object())
../ENV/lib/python3.8/site-packages/werkzeug/local.py:306: in _get_current_object
    return self.__local()
../ENV/lib/python3.8/site-packages/flask_login/utils.py:26: in <lambda>
    current_user = LocalProxy(lambda: _get_user())
../ENV/lib/python3.8/site-packages/flask_login/utils.py:346: in _get_user
    current_app.login_manager._load_user()

---------------------------------------------------------------------------------------------------------------

```
self = <flask_ad_auth.ad_login.ADAuth object at 0x7fa163b183d0>

    def _load_user(self):
        '''Loads user from session or remember_me cookie as applicable'''
    
        if self._user_callback is None and self._request_callback is None:
>           raise Exception(
                "Missing user_loader or request_loader. Refer to "
                "http://flask-login.readthedocs.io/#how-it-works "
                "for more info.")
E           Exception: Missing user_loader or request_loader. Refer to http://flask-login.readthedocs.io/#how-it-works for more info.

../env/lib/python3.8/site-packages/flask_login/login_manager.py:302: Exception
```


this happens since updating flask-login from version 0.4.1 to 0.5.0
